Add routing
Simutyte/PSI1-EncounterMe pull request #58
Opened 2021-11-15 09:55 UTC by povilassl

2021-11-15 15:14 UTC, RositaRai commented on EncounterMe/EncounterMe/Views/MapPage.xaml.cs
> +            Console.WriteLine("-------------------------------------------------------------------------------------");
Šituos gal jau gali ištrint :D

2021-11-15 15:16 UTC, RositaRai commented on EncounterMe/EncounterMe/Views/MapPage.xaml.cs
> +
Emphy line

2021-11-15 15:17 UTC, povilassl commented on EncounterMe/EncounterMe/Views/MapPage.xaml.cs
> +            Console.WriteLine("-------------------------------------------------------------------------------------");
tai jo

2021-11-15 15:17 UTC, povilassl commented on EncounterMe/EncounterMe/Views/MapPage.xaml.cs
> +
nekomentuok dar, tuoj taisau viska

2021-11-15 15:19 UTC, RositaRai commented on EncounterMe/EncounterMe/Views/MapPage.xaml.cs
> +
Empty line

2021-11-16 18:36 UTC, Simutyte commented
Viskas labai gerai. Nebent būtų galima padaryt (kaip anksčiau), jog jei neranda maršruto ir tu esi per toli, tai išeitų ir iš to žemėlapio, nes dabar patenka į tą puslapį, kur maršrutą turėtų rodyt ir yra meniu maršruto, nors to maršruto nėra

2021-11-16 18:37 UTC, Simutyte requested changes
Viskas labai gerai. Nebent būtų galima padaryt (kaip anksčiau), jog jei neranda maršruto ir tu esi per toli, tai išeitų ir iš to žemėlapio, nes dabar patenka į tą puslapį, kur maršrutą turėtų rodyt ir yra meniu maršruto, nors to maršruto nėra

2021-11-16 18:38 UTC, Simutyte approved these changes

2021-11-16 19:18 UTC, merged